name: CI
on:
  push:
    paths:
    - '.github/workflows/ci.yml'
    - '**.js'
    - '**.eslintrc.json'
    - 'package.json'
    - 'package-lock.json'
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 24
      uses: actions/setup-node@v3
      with:
        node-version: 24.x
    - run: npm ci
    - run: node --test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 24
      uses: actions/setup-node@v3
      with:
        node-version: 24.x
    - run: npm ci
    - run: node --run lint
