name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --prefer-offline
    - run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-
    - run: npm ci --prefer-offline
    - run: npm run lint
