name: Pull Request
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - run: npm ci
    - run: npm test
