name: Publish Scheduled Posts
on:
  schedule:
  - cron: 0/15 * * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 20
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: publish scheduled
      env:
        BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
      run: node scripts/publish-scheduled.js
