name: Publish Scheduled Posts
on:
  schedule:
  - cron: 0/15 * * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 14
      uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: npm ci
    - name: publish scheduled
      env:
        NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
      run: node scripts/publish-scheduled.js
