name: Publish Scheduled Posts
on:
  schedule:
  - cron: 0/15 * * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 14
      uses: actions/setup-node@main
      with:
        node-version: '14.x'
    - run: npm ci
    - name: publish scheduled
      env:
        BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
      run: node scripts/publish-scheduled.js
