on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/notes/*.json'
      - 'content/links/*.json'
jobs:
  get-added-files:
    runs-on: ubuntu-latest
    outputs:
      note: ${{ steps.added-documents.outputs.documents }}
    steps:
    - name: checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 2
    - name: Get added documents
      id: added-documents
      run: echo "documents=$(git diff --name-only --diff-filter=A ${{ github.sha }}{^,} | grep -e ^content/notes/ -e ^content/links/ | xargs)" > $GITHUB_OUTPUT
  syndicate-to-mastodon:
    needs: get-added-files
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Dispatch mastodon API call
      env:
        MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      run: node scripts/syndicate-to-mastodon.js ${{ needs.get-added-files.outputs.documents }}
