name: Syndicate to Bluesky
on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/notes/*.json'
      - 'content/links/*.json'
jobs:
  get-added-files:
    runs-on: ubuntu-latest
    outputs:
      documents: ${{ steps.added-documents.outputs.documents }}
    steps:
    - name: checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 2
    - name: Get added documents
      id: added-documents
      run: echo "documents=$(git diff --name-only --diff-filter=A ${{ github.sha }}{^,} | grep -e ^content/notes/ -e ^content/links/ | xargs)" > $GITHUB_OUTPUT
  syndicate-to-bluesky:
    needs: get-added-files
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 24
      uses: actions/setup-node@v3
      with:
        node-version: 24.x
    - name: Dispatch bluesky API calls
      run: node scripts/syndicate-to-bluesky.js --handle qubyte.codes --app-password ${{ secrets.BLUESKY_APP_PASSWORD }} ${{ needs.get-added-files.outputs.documents }}
