on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/links/*.json'
jobs:
  get-added-files:
    runs-on: ubuntu-latest
    outputs:
      link: ${{ steps.added-notes.outputs.link }}
    steps:
    - name: checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 2
    - name: Get added links
      id: added-links
      run: echo "link=$(git diff --name-only --diff-filter=A ${{ github.sha }}{^,} | grep ^content/links/ | xargs)" > $GITHUB_OUTPUT
  syndicate-to-mastodon:
    needs: get-added-files
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main
    - name: use node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - name: Dispatch mastodon API call
      env:
        MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      run: node scripts/syndicate-link-to-mastodon.js ${{ needs.get-added-files.outputs.link }}
