name: Update Copyright Notice
on:
  schedule:
  - cron: 0 0 1 1 *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - run: npm ci
    - name: trigger build
      env:
        NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
      run: node scripts/trigger-build
